<a href="https://colab.research.google.com/github/haley3y/ITP_ML/blob/main/HW2_Pandas_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# psy or teacher
import pandas as pd
df = pd.DataFrame(data)

# fil = df[df["job"].isin(["psychologist","teacher"])& (df["num_cars"]> df["family_size"])]
# print(fil)

# print(df[(df["family_size"]<=2) & (df["num_cars"] >=1)])

print(len(pd.array(df["job"]).unique()))

print(len(set(df["job"]))) # use max & get unique results

4
4


In [ ]:
# Type your solution here
import pandas as pd

# Q1-1: Write a program that create a dataframe from the data
df = pd.DataFrame(data)
print(df)

# Q1-2: Select people that are psychologist or teacher and their number of cars is greater than their family size.
df_con1 = df[(df["job"]=="psychologist") | (df["job"]=="teacher")]
df_con2 = df_con1[(df_con1["num_cars"])>(df_con1["family_size"])]
print(df_con2)

# Q1-3: Select people who have at most 2 family members and at least 1 car.
df_con3 = df[(df["family_size"]<=2) & (df["num_cars"]>=1)]
print(df_con3)

# Q1-4: Write a code that get number of unique jobs in this dataset.
print(len(df["job"].unique()))

1:      name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
2:    name           job  family_size  num_cars
5  Lisa  psychologist            3         4
3:     name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
4: 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
weights.groupby(fruit).mean()

apple     8.000000
banana    2.333333
carrot    6.000000
dtype: float64

In [ ]:
# Type your solution here
# Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.
fruit_info = pd.DataFrame({"fruit":fruit, "weights":weights})
#print(fruit_info)

# print(fruit_info["fruit"].unique())

# mean weights of apple
apple = fruit_info[fruit_info.fruit == "apple"]
a_wg = np.mean(apple.weights)
print("Mean weights of apple:", a_wg)

# mean weights of carrot
carrot= fruit_info[fruit_info.fruit == "carrot"]
c_wg = np.mean(carrot.weights)
print("Mean weights of carrot:", c_wg)

# mean weights of banana
banana= fruit_info[fruit_info.fruit == "banana"]
# print(banana)
b_wg = np.mean(banana.weights)
print("Mean weights of banana:", b_wg)


Mean weights of apple: 8.0
Mean weights of carrot: 6.0
Mean weights of banana: 2.3333333333333335


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
# Q3-1: Write a NumPy program to get the indices of the sorted elements of course_name array.
sort_i = np.argsort(course_name)
print(sort_i)

# Q3-2: Write numpy code to check whether each element of course_name array starts with "P".
check_p = np.char.startswith(course_name, "P")
print(check_p)


[1 3 0 2 4]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# print(student_id)
# print(student_id[::-1])


# hav to be within numpy
sorted = np.unique(np.sort(student_id))
print(sorted[-3:])
# sorted[0:len(sorted):-1]

[5202 5241 6230]


In [ ]:
# Type your solution here

# Q4-1: Reverse the student_id array. Print both original and reversed array.
print("oringinal:", student_id)
student_id_re = student_id[::-1]
# print reversed array
print("reversed:", student_id_re)

# Q4-2: Get the 3-largest values of student_id array.
stud_sort = np.sort(student_id)
# print(stud_sort)

# ensure no duplicate value
stud_unique = np.unique(stud_sort)

# subset the top 3 values
top_3 = stud_unique[-3:]
print("top3:", top_3)

oringinal: [1023 1671 1682 4532 5202 5241 6230]
reversed: [6230 5241 5202 4532 1682 1671 1023]
top3: [5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
test_arr = np.arange(1, 150, 2)

con_q5 = test_arr[((test_arr%3 ==0)|(test_arr%5 ==0)) &(test_arr<100)]
# print(con_q5)

sum_q5 = sum(con_q5)
print(sum_q5)

# Hint: you can use arange to start off

1232


In [ ]:
test_arr = np.arange(1, 150, 2)

result = test_arr[((test_arr%3 == 0)|(test_arr%5 == 0)) & (test_arr<100)]
print(result)

print(sum(result))

[ 3  5  9 15 21 25 27 33 35 39 45 51 55 57 63 65 69 75 81 85 87 93 95 99]
1232


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

# arr[:,[2,1]] = arr[:,[1,2]]
# print(arr)

arr2 = np.arange(12).reshape(3,4)
arr2[[1,0],:] = arr2[[0,1]
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 1  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
arr2 = np.arange(12).reshape(3,4)

# Q6.1. Write a code to swap column 1 with column 2.
arr[:,[1,2]] = arr[:,[2,1]]
print(arr)

# Q6.2. Write a code to swap row 0 with row 1.
arr2[[0,1],:] = arr2[[1,0],:]
print(arr2)

[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
